# Generated by Django 6.1.1 on 2026-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
