# Generated by Django 6.1.1 on 2026-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL to profile picture', max_length=500),
        ),
    ]
