# Generated by Django 6.1 on 2026-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_initials',
            field=models.CharField(blank=True, help_text='Override letters shown in the avatar (e.g. MI).', max_length=4),
        ),
    ]
